// Ashtonk!mania build: inlines src/styles.css and src/js/*.js into a single index.html (+ public/index.html for hosting).
// Usage: node build.mjs
import { readFileSync, writeFileSync, readdirSync, mkdirSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const tpl = readFileSync(join(root, 'src/index.template.html'), 'utf8');
const css = readFileSync(join(root, 'src/styles.css'), 'utf8');
const jsDir = join(root, 'src/js');
const js = readdirSync(jsDir).filter(f => f.endsWith('.js')).sort()
  .map(f => `/* ===== ${f} ===== */\n` + readFileSync(join(jsDir, f), 'utf8')).join('\n');
const out = tpl
  .replace('/*__CSS__*/', () => css)
  .replace('/*__JS__*/', () => '"use strict";\n' + js);
writeFileSync(join(root, 'index.html'), out);
// public/ is what Cloudflare serves (see wrangler.jsonc): only the built client, never sources or tests.
mkdirSync(join(root, 'public'), { recursive: true });
writeFileSync(join(root, 'public', 'index.html'), out);
// the service worker (offline play) carries the build's hash, so browsers update it after each deploy
const version = createHash('sha256').update(out).digest('hex').slice(0, 12);
writeFileSync(join(root, 'public', 'sw.js'), readFileSync(join(root, 'src/sw.js'), 'utf8').replace('__VERSION__', version));
console.log(`index.html written (${(out.length / 1024).toFixed(1)} KiB)`);
// the game server's score judge: the same parsing, judging and pp code as the game (see src/js/09c-verify.js)
const VERIFY_FILES = ['00-util.js', '03-beatmap-parser.js', '03b-mania-convert.js', '08-mods.js', '09-gameplay.js', '09a-osu-math.js', '09c-verify.js'];
writeFileSync(join(root, 'worker', 'verify-bundle.js'), '// GENERATED by build.mjs from src/js — do not edit.\n' +
  VERIFY_FILES.map(f => `/* ===== ${f} ===== */\n` + readFileSync(join(jsDir, f), 'utf8')).join('\n') + '\nexport { verifyPlay };\n');
